name: Maven + Codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Check EditorConfig compliance
        uses: editorconfig-checker/action-editorconfig-checker@v2
        with:
          fail-on-warnings: true

      - name: Run style check (Checkstyle)
        run: mvn checkstyle:check

      - name: Build (Debug)
        run: mvn clean compile

      - name: Build (Release)
        run: mvn clean package -P release

      - name: Run unit tests + generate coverage
        run: mvn test jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Upload Javadoc as artifact
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/reports/apidocs
